#!/bin/bash
#PBS -N 340K_10ACN_1V
#PBS -l nodes=2:ppn=24
#PBS -l walltime=01:00:00

JOB="340K_10ACN_1V"
DATADIR="$HOME/data/$JOB"
INPUTDIR=/zhome/academic/HLRS/icp/icpkonra/git/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI/340K/10ACN/1V

mkdir -p $DATADIR/
cd $DATADIR
rm *out* testout*

cp $INPUTDIR/potential.inpt $INPUTDIR/restart.dat $INPUTDIR/runtime.inpt ./

aprun -n 48 -N 24 $HOME/src/metalwalls/bin/metalwalls.exe
