#!/bin/bash
#PBS -N CDC_EQUIRUN_PREFILLED
#PBS -l nodes=2:ppn=24
#PBS -l walltime=12:00:00 

JOB="0V_330K_0ACN_1BAR_EQUIRUN_PREFILLED"
INPUTDIR="$HOME/git/md-sim/metalwalls/inputfiles/EMIBF4_ACN_CDC8x/0V_330K_0AC_1BAR"
DATADIR="$HOME/data/$JOB"

mkdir -p $DATADIR/
cd $DATADIR
rm *out* testout*

cp $INPUTDIR/potential.inpt $INPUTDIR/restart.dat $INPUTDIR/runtime.inpt ./

#-j 2 enables Hyperthreading
aprun -n 48 -N 24 $HOME/src/metalwalls/bin/metalwalls.exe
