qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/0ACN/0V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/0ACN/1V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/0ACN/2V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/10ACN/0V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/10ACN/1V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/10ACN/2V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/40ACN/0V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/40ACN/1V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/40ACN/2V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/20ACN/0V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/20ACN/1V/job.pbs
qsub /work1/uqrburt/metalwalls/runs/md-sim/metalwalls/EMIBF4_ACN_CDC8x/EQUI_barrine/298K/20ACN/2V/job.pbs
